name: course2020
channels:
   - conda-forge
dependencies:
   - python=3.8
   - ipython
   - jupyter
   - spyder
   - numpy
   - matplotlib
   - pandas
   - xlrd
   - xlwt
   - cartopy=0.18
   - xarray
   - seaborn
   - netcdf4
   - dask
